### ISSUE TITLE
Samples not working

### ISSUE THREAD

**Issue by programisti** [joshnuss/xml_builder#11]
Most of samples provided on readme not working

this is my module

```elixir
defmodule Test do  
  def run do
    {:person, %{id: 12345}, "Josh"} |> XmlBuilder.generate
  end
end
```
After running Test.run this error comes:
** (FunctionClauseError) no function clause matching in XmlBuilder.generate/2
    lib/xml_builder.ex:68: XmlBuilder.generate({:person, %{id: 12345}, "Josh"}, 0)

```elixir

defmodule Test do
   def run do
     {:person, %{id: 12345}, [{:first, nil, "Josh"}, {:last, nil, "Nussbaum"}]} |> XmlBuilder.generate
   end 
end
```
When I run Test.run it is throwing error message:
screen: http://screencloud.net/v/bi2l
iex(1)> Test.run
** (FunctionClauseError) no function clause matching in XmlBuilder.generate/2
    lib/xml_builder.ex:68: XmlBuilder.generate({:person, %{id: 12345}, [{:first, nil, "Josh"}, {:last, nil, "Nussbaum"}]}, 0)

I am running 0.0.7 version of xml_builder, also tried 0.0.6 

This works
```elixir
XmlBuilder.doc(:person, "Josh")
```

This sample not working:
```elixir
defmodule Test do
  import XmlBuilder
          
  def run do
    [person(123, "Steve", "Jobs"),
       person(456, "Steve", "Wozniak")] |> generate
  end
    
  def person(id, first, last) do
     element(:person, %{id: id}, [
       element(:first, first),
       element(:last, last)
     ])
  end  
end
```
After running Test.run it is throwing this error
iex(1)> Test.run
** (FunctionClauseError) no function clause matching in XmlBuilder.element/1
                 lib/xml_builder.ex:35: XmlBuilder.element({:element, :first, nil, "Steve"})
        (elixir) lib/enum.ex:1049: Enum.map/2
                 lib/xml_builder.ex:51: XmlBuilder.element/1
    (ndc_ex_sdk) lib/test.ex:5: Test.run/0

screen: http://screencloud.net/v/y5Q0

This works fine
```elixir
defmodule Test do
   import XmlBuilder
          
   def run do
      person(123, "Josh", "Nussbaum") |> generate
   end                                 
                                        
   def person(id, first, last) do      
     element(:person, %{id: id}, first: first, last: last)
   end 
end
``` 
Do I have any alternative to build xml with Elixir?

**Comment by programisti** [comment]
I really need this package, but as you see I can not use even samples

**Comment by matteosister** [comment]
same problem here. Revert to 0.0.6 and all examples works. Probably there is an unwanted api change between the two versions. @joshnuss could you please take a look? Many thanks.

**Comment by programisti** [comment]
@matteosister what version of Elixir are you running?
Can you post your mix.exs file?

**Comment by matteosister** [comment]
1.1.1!

here it is:

``` elixir
defmodule MyApp.Mixfile do
  use Mix.Project

  def project do
    [app: :my_app,
     version: "0.1.0",
     elixir: "~> 1.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix] ++ Mix.compilers,
     build_embedded: Mix.env == :prod || Mix.env == :staging,
     start_permanent: Mix.env == :prod || Mix.env == :staging,
     aliases: aliases,
     deps: deps]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {MyApp, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger,
                    :phoenix_ecto, :mariaex, :httpoison, :xml_builder,
                    :exmerl, :xmerl, :timex, :redix]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(:circle), do: elixirc_paths(:test)
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "~> 1.1"},
     {:phoenix_ecto, "~> 1.1"},
     {:mariaex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"},
     {:xml_builder, "~> 0.0.6"},
     {:httpoison, "~> 0.8.0"},
     {:exmerl, "~> 0.1.1"},
     {:timex, "~> 0.19"},
     {:redix, ">= 0.0.0"},
     {:exrm, "~> 0.19.9"}]
  end

  # Aliases are shortcut or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"]]
  end
end

```

**Comment by joshnuss** [comment]
Thanks @programisti for reporting.

Looks like the PR for adding support for xml comments broke the samples.

I've reverted that code and pushed a new version [v0.0.8](https://hex.pm/packages/xml_builder/0.0.8)

**Comment by matteosister** [comment]
@joshnuss thanks for the quick fix! Everything works perfectly as 0.0.6 now!

**Comment by xurde** [comment]
Great support here, guys. :+1:

**Comment by programisti** [comment]
Thank you @joshnuss you saved us.
