### ISSUE TITLE
Leverage IO lists to improve performance

### ISSUE THREAD

**Issue by lpil** [joshnuss/xml_builder#17]
Hello!

It seems that currently this lib works through binary concatenation. We should be able to improve encoding speed and reduce memory usage by using IO lists instead :)

I'd be great to see some benchmarks added and then then seeing how the IO data implementation compares.

Cheers,
Louis

**Comment by joshnuss** [comment]
Hi @lpil!

That's a good point, never thought of doing that. I think it should speed things up.

Feel free if you'd like to add it, otherwise I will get to it when I have some time.

Cheers,
Josh

**Comment by lpil** [comment]
Ace. Thanks Josh. I may submit a PR if I find time :)

**Comment by joshnuss** [comment]
Thanks for the suggestion, I converted everything to iodata.

As a nice side effect, it's gonna make it way easier to refactor the formatting logic.

Cheers!

**Comment by lpil** [comment]
Thank you :)

**Comment by lpil** [comment]
There's still a few instances of `Enum.map_join/3` that I'd expect to be slower than using iolists, but hard to say without benchmarks
