### ISSUE TITLE
Not able to use XML Entities

### ISSUE THREAD

**Issue by elijahkim** [joshnuss/xml_builder#21]
I'm trying to add a linefeed in my XML but it's translating `&` like such:

```
iex(11)> XmlBuilder.generate({:thing, %{}, "hello &#xA; world"})
"<thing>hello &amp;#xA; world</thing>"
```

Is there a way to escape characters or to straight up use xml entities?

**Comment by joshnuss** [comment]
Currently there isn't support for entities. But I'd be open to adding it.

It would need to wait on #13, as that will allow options to be passed to `generate`. ie `generate(xml_nodes, entities: ~w(copyright writer))`

**Comment by joshnuss** [comment]
Closing, but feel free to open a PR and I'd be happy to merge.
