### ISSUE TITLE
Using if condition to make tags

### ISSUE THREAD

**Issue by arjun289** [joshnuss/xml_builder#24]
This is more of a question than an issue. Is there a way to use if condition inside element tags?
e.g.
element(:tags, 
              if (x == true)
                [element(:true)]
              else
                [element(:false)])

**Comment by joshnuss** [comment]
Hi @arjun289!

You can use an `if`, ie. `element(:tags, if x, do: element(true), else: element(false))`

It's better to use pattern matches (instead of conditionals)

```elixir
def country(code, region),
   do: element(:country, region(code, region)

def region("US", state),
  do: element(:state, state)

def region("CA", province),
  do: element(:province, province)

```

**Comment by arjun289** [comment]
Thanks!!
