### ISSUE TITLE
The Repo on Hex isn't updated

### ISSUE THREAD

**Issue by cseagull** [joshnuss/xml_builder#25]
When getting xml_builder from hex `{:xml_builder, "~> 0.1.1"}` the function doctype is missing!

When getting xml_builder directly from Github `{:xml_builder, git: "https://github.com/joshnuss/xml_builder"}` the function doctype is avalible

**Comment by joshnuss** [comment]
Just updated it to `0.1.2`

Thanks for reporting @cseagull!
