### ISSUE TITLE
`format: :none` is ignored when using XmlBuilder.doc

### ISSUE THREAD

**Issue by amencarini** [joshnuss/xml_builder#27]
I am in the process of switching from pre-v1 to 2.0.0 and I'm struggling with the changes, especially around the different APIs of `.doc` and `.generate`. To get compact XML output I'm having to add empty maps on every element that has no attributes, and use `.generate(format: :none)`, as if I use `.doc` at any time I get whitespace all over the XML document.

Is there a way I can avoid doing this? Thanks in advance!

**Comment by joshnuss** [comment]
Hi @amencarini,

Can you share some example code of the issue you're having, I'll take a look

**Comment by amencarini** [comment]
```
iex(1)> XmlBuilder.doc({:html, [{:body, "Hello world"}]})
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<html>\n  <body>Hello world</body>\n</html>"
iex(2)> XmlBuilder.doc({:html, [{:body, "Hello world"}]}) |> XmlBuilder.generate(format: :none)
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<html>\n  <body>Hello world</body>\n</html>"
iex(3)> XmlBuilder.generate({:html, %{}, [{:body, %{}, "Hello world"}]}, format: :none)
"<html><body>Hello world</body></html>"
```

What I'd love is a way to use the `doc` function, for it to accept the `format: :none` option so that whitespace gets removed. I would like not to have to add empty maps for attributes for all elements and use `generate` to get a whitespace free XML document.

Is that something that can be currently achieved? This was working fine pre 2.0.0.

**Comment by joshnuss** [comment]
Thanks @amencarini,

Think the issue is that `doc/2` & `doc/3` return a `string`, it should really return a tree of tuples. 
Maybe I should introduce a new function `document/2` & `document/3` to replace `doc` (ie deprecate `doc`)
That would force people to call `generate/2` and choose formatting options

Thoughts?

**Comment by amencarini** [comment]
That would work perfectly for us!

**Comment by joshnuss** [comment]
@amencarini should be all good now :ok_hand: 

Let me know if you run into any other issues, and thanks for reporting this issue! :1st_place_medal:
