### ISSUE TITLE
Backslash character remove from xml issue

### ISSUE THREAD

**Issue by RameshSharmaGithub** [joshnuss/xml_builder#38]
How to remove the backslash character from xml in elixir:-
String.replace("\"", "&quot;") is not working for my case.

I need String.replace("\", ""). Please suggest how to achieve it.

**Comment by joshnuss** [comment]
Hi @RameshSharmaGithub,

Can you provide some more details?
Which backslash?
Can you show before and after examples of what your looking to do?

**Comment by RameshSharmaGithub** [comment]
Hi @joshnuss 
I have generated an xml using the library as below, pasting a part of the xml:-

"<soapenv:Envelope xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:urn=\"urn:idu\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <soapenv:Body>\n    <urn:IDUProcess soapenv:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">\n "

 
I want to remove the backslash characters from the generated xml. I tried String.replace("\", "") but it did not worked.
I tried String.replace("\"", "&quot;"), it works but this is not what I want.

Can you please suggest.

**Comment by RameshSharmaGithub** [comment]
I am seeing that as I am commenting above in the comments box, the backslash is getting removed. Once you click on the three dots in the box and Edit my comments then you will be able to see my comments properly.

**Comment by joshnuss** [comment]
I think you want to sanitize before generating the XML.

For example:

```elixir
content = String.replace(..., ...)
element(:example, content) |> generate ()
```

Instead of

```elixir
content = String.replace(..., ...)
element(:example, content) |> generate()
```

**Comment by RameshSharmaGithub** [comment]
The generated xml has the backslash characters introduced which I want to remove. So I have executed as below, but no output. Can you please rearrange it if required:-

iex:18> [{:'soapenv:Envelope', %{"xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance", "xmlns:xsd": "http://www.w3.org/2001/XMLSchema", "xmlns:soapenv": "http://schemas.xmlsoap.org/soap/envelope/", "xmlns:urn": "urn:idu", "xmlns:soapenc": "http://schemas.xmlsoap.org/soap/encoding/"}, [{:'soapenv:Body', %{}, [{:'urn:IDUProcess', %{"soapenv:encodingStyle": "http://schemas.xmlsoap.org/soap/encoding/"}, [{:params, %{"xsi:type": "urn:Request"}, [{:IDU, %{"xsi:type": "urn:IDUDetails"}, [{:Reference, %{"xsi:type": "xsd:string"}, "Ref123"}, {:ID, %{"xsi:type": "xsd:string"}, ""}, {:IKey, %{"xsi:type": "xsd:string"}, ""}, {:Scorecard, %{"xsi:type": "xsd:string"}, "Legal and General Fusion"}]},{:Login, %{"xsi:type": "urn:LoginDetails"}, [{:username, %{"xsi:type": "xsd:string"}, ""}, {:password, %{"xsi:type": "xsd:string"}, ""}]}, {:Person, %{"xsi:type": "urn:PersonDetails"}, [{:forename, %{"xsi:type": "xsd:string"}, "JACK"}, {:middle, %{"xsi:type": "xsd:string"}, "MATTHEW"}, {:surname, %{"xsi:type": "xsd:string"}, "DAVIES"}, {:dob, %{"xsi:type": "xsd:string"}, "1978-08-07"}, {:address1, %{"xsi:type": "xsd:string"}, "230"}, {:address2, %{"xsi:type": "xsd:string"}, "Julius Road Bristol"}, {:postcode, %{"xsi:type": "xsd:string"}, "BS7 8EU"}]}, {:Services, %{"xsi:type": "urn:ServiceDetails"}, [{:address, %{"xsi:type": "xsd:boolean"}, "TRUE"}, {:dob, %{"xsi:type": "xsd:boolean"}, "TRUE"}, {:crediva, %{"xsi:type": "xsd:boolean"}, "TRUE"}, {:creditactive, %{"xsi:type": "xsd:boolean"}, "TRUE"}]}]}]}]}]}] |> generate |> String.replace("\", "")
...:18>

**Comment by RameshSharmaGithub** [comment]
If you 'import XmlBuilder' and then run the above till |> generate then you will be able to see the xml generated like below with the backslash characters which I want to remove:-

"<soapenv:Envelope xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:urn=\"urn:idu\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n  <soapenv:Body>\n    <urn:IDUProcess soapenv:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">\n      <params xsi:type=\"urn:Request\">\n        <IDU xsi:type=\"urn:IDUDetails\">\n          <Reference xsi:type=\"xsd:string\">Ref123</Reference>\n          <ID xsi:type=\"xsd:string\"></ID>\n          <IKey xsi:type=\"xsd:string\"></IKey>\n          <Scorecard xsi:type=\"xsd:string\">Legal and General Fusion</Scorecard>\n        </IDU>\n        <Login xsi:type=\"urn:LoginDetails\">\n          <username xsi:type=\"xsd:string\"></username>\n          <password xsi:type=\"xsd:string\"></password>\n        </Login>\n        <Person xsi:type=\"urn:PersonDetails\">\n          <forename xsi:type=\"xsd:string\">JACK</forename>\n          <middle xsi:type=\"xsd:string\">MATTHEW</middle>\n          <surname xsi:type=\"xsd:string\">DAVIES</surname>\n          <dob xsi:type=\"xsd:string\">1978-08-07</dob>\n          <address1 xsi:type=\"xsd:string\">230</address1>\n          <address2 xsi:type=\"xsd:string\">Julius Road Bristol</address2>\n          <postcode xsi:type=\"xsd:string\">BS7 8EU</postcode>\n        </Person>\n        <Services xsi:type=\"urn:ServiceDetails\">\n          <address xsi:type=\"xsd:boolean\">TRUE</address>\n          <dob xsi:type=\"xsd:boolean\">TRUE</dob>\n          <crediva xsi:type=\"xsd:boolean\">TRUE</crediva>\n          <creditactive xsi:type=\"xsd:boolean\">TRUE</creditactive>\n        </Services>\n      </params>\n    </urn:IDUProcess>\n  </soapenv:Body>\n</soapenv:Envelope>"

**Comment by RameshSharmaGithub** [comment]
It is resolved now. Closing the issue.

**Comment by Sebi55** [comment]
@RameshSharmaGithub @joshnuss  I am having the same problem. I pass a clean string with an url into an attribute and the string is getting escaped so that attribute=\"http://....\" occurs in the output instead of just attribute="http://....".

Why is that and how can I remove the backslash from the output? Replacing seems like a really bad solution.

**Comment by joshnuss** [comment]
Hi, can you share a code example? That would help me understand the problem
better.
