### ISSUE TITLE
How to deal with namespaces?

### ISSUE THREAD

**Issue by eddy147** [joshnuss/xml_builder#47]
It is unclear to me how to create Xml with namespaces.
For example:

`<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
       <IndienenBerichtResponse xmlns="http://schemas.vecozo.nl/berichtuitwisseling/v3">
          <IndienenBerichtResult>
             <ConversatieId xmlns="http://schemas.vecozo.nl/berichtuitwisseling/messages/v3">fc6d5c90-5630-4270-aba2-bc1be7936502</ConversatieId>
             <TraceerId xmlns="http://schemas.vecozo.nl/berichtuitwisseling/messages/v3">fc6d5c90-5630-4270-aba2-bc1be7936502</TraceerId>
          </IndienenBerichtResult>
       </IndienenBerichtResponse>
    </s:Body>
 </s:Envelope>`

How to add s as a namespace using generate?

**Comment by devstopfix** [comment]
One approach, hard-coding the prefix - is

```elixir
iex(1)> XmlBuilder.generate({:"s:Envelope", [{:"xmlns:s", "http://schemas.xmlsoap.org/soap/envelope/"}], []})

"<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"/>"
```

**Comment by eddy147** [comment]
That's what I did, and it works nicely, I just thought I missed some option or something.
So if this is the way, then I will do it as such.
Thx for the reply.

**Comment by joshnuss** [comment]
@eddy147 the solution @devstopfix mentioned is correct.

I've updated the `README` to include an example.

**Comment by eddy147** [comment]
Thx for the update in the README.
